mysql:
    image: mysql:5.7
    ports:
        - "3310:3310"
    restart: always
    environment:
        MYSQL_DATABASE: sample_db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: rootpassword
